<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <RootNamespace>DiskMigrator.Windows</RootNamespace>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\DiskMigrator.Core\DiskMigrator.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="AlphaVSS" Version="2.0.3" />
    <PackageReference Include="System.Management" Version="8.0.0" />
  </ItemGroup>

</Project>
